let menuRu, menuEn, menuKz;
menuRu = {
  gen: 'Главная',
  about: 'О компании',
  news: 'Новости',
  product: 'Продукция и услуги',
  carer: 'Вакансии',
  contact: 'Контакты',
  product1: 'Производство и продукция',
  product2: 'Услуги и сервис',
  product3: 'Лаборотория',
  certif:'Сертификаты',
  partner:'Партнеры',
  fnews:'Все новости',
  fcertif:'Все сертификаты',
  too:'ТОО «АТЫРАУНЕФТЕМАШ»',
  titleMenuFuter:'Разделы сайта',
  titleMenuFuter2:'Реквизиты',
  adminp:'Панель администратора',
  perdate:'Обработка персональных данных',
  polit:'Политика конфиденциальности',
  razrab:'Разработчик:',
  titledirector:'Руководители компании',
};
menuEn =
{
  gen: 'Home page',
  about: 'About the company',
  news: 'News',
  product: 'Products and services',
  carer: 'Vacancy',
  contact: 'Contacts',
  product1: 'Production and products',
  product2: 'Services and Service',
  product3: 'Laboratory',
  certif:'Certificates',
  partner:'Partners',
  fnews:'All news',
  fcertif:'All certificates',
  too:'ATYRAUNEFTEMASH LLP',
  titleMenuFuter:'Site Sections',
  titleMenuFuter2:'Requisites',
  adminp:'Admin Panel',
  perdate:'Processing of personal data',
  polit:'Privacy Policy',
  razrab:'Developer:',
  titledirector:'Company managers',
};
menuKz = {
  gen: 'Басты бет',
  about: 'Компания туралы',
  news: 'Жаңалықтар',
  product: 'Өнімдер мен қызметтер',
  carer: 'Жұмыс',
  contact: 'Байланыстар',
  product1: 'Өндіріс және өнім',
  product2: 'Қызметтер және қызмет',
  product3: 'Зертхана',
  certif:'Сертификаттар',
  partner:'Серіктестер',
  fnews: 'Барлық жаңалықтар',
  fcertif:'Барлық сертификаттар',
  too:'ЖШС «АТЫРАУНЕФТЕМАШ»',
  titleMenuFuter:'Сайт бөлімдері',
  titleMenuFuter2:'Деректемелер',
  adminp: 'Әкімші тақтасы',
  perdate: 'Жеке деректерді өңдеу',
  polit:'Құпиялылық саясаты',
  razrab:'Әзірлеуші:',
  titledirector:'Компания басшылары',
};